# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73b3b8eef2eac141ddf9984ba3f856e312dae0e00233b5bc5378d1d687998a12d750db9385e2882ef82513a0f1a9f5041db107da19916b40556166277e35d2b3

test:
  secret_key_base: d27224b2be959d92fcc51d89c744c4b665089ba3ef74d9d76b88089c51051330e4d9380ce123c388187ce94181fd6c5dc7cebd31af808c192c20e106994d5020

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
